import type { Metadata } from "next";
import { Geist, Geist_Mono, Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Script from "next/script";


import GlobalCursor from "@/components/GlobalCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const vietnam = Be_Vietnam_Pro({

  subsets: ["latin"],

  weight: ["100","200","300","400","500","600","700","800","900"],

  variable: "--font-vietnam",

});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${vietnam.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <link rel="preload" href="/chipgif3.svg" as="image" />
        <GlobalCursor />
        {children}
                <Script
          src="https://cdn.botpress.cloud/webchat/v3.6/inject.js"
          strategy="lazyOnload"
        />

        <Script
          src="https://files.bpcontent.cloud/2026/06/18/16/20260618163539-F2RYSAYV.js"
          strategy="lazyOnload"
        />

        <Toaster
    position="top-right"
    richColors
    theme="dark"
  />
      </body>
    </html>
  );
}