import type { Metadata } from "next";
import { Geist, Geist_Mono, Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import GlobalCursor from "@/components/GlobalCursor";
import BotpressScripts from "@/components/BotpressScripts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const vietnam = Be_Vietnam_Pro({

  subsets: ["latin"],

  weight: ["100","200","300","400","500","600","700","800","900"],

  variable: "--font-vietnam",

});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${vietnam.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GlobalCursor />
        {children}
                <BotpressScripts />

        <Toaster
    position="top-right"
    richColors
    theme="dark"
  />
      </body>
    </html>
  );
}